name: Coverage Report

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COREPACK_ENABLE_STRICT: 0

jobs:
  inspect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          corepack enable
          pnpm install
          npx lerna run test:coverage
      - name: Setup Pages
        if: ${{ always() }}
        uses: actions/configure-pages@v2
      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the coverage directory from the repository
          path: ".packages/npmrc/coverage/lcov-report"
      - name: Deploy to GitHub Pages
        if: ${{ always() }}
        id: deployment
        uses: actions/deploy-pages@v1
