name: Check Pull Requests
on:
  pull_request:
    branches: [main]
permissions:
  statuses: write
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set commit status as pending
        uses: ouzi-dev/commit-status-updater@v2
      - run: npx lerna bootstrap
      - run: npx lerna run lint
      - run: npx lerna run test:coverage
