name: Inspect Pull Requests

on:
  pull_request:
    branches: [main]

jobs:
  inspect:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable
      - run: yarn set version berry
      - run: yarn install
      - run: npx lerna run build
      - run: npx lerna run lint
      - run: npx lerna run test:coverage
